# Generated by Django 3.2.25 on 2026-04-13 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='energy_required',
            field=models.CharField(choices=[('low', 'Low Battery'), ('med', 'Steady Flow'), ('high', 'Hyperfocus')], default='med', max_length=10),
        ),
        migrations.AddField(
            model_name='habit',
            name='is_micro_ritual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='energy_level',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='focus_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='habit',
            name='streak',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='EvidenceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('habit_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
