# Mental Health Aligned Ritual Presets
RITUAL_PRESETS = [
    {"name": "Social Grounding", "sustainable": "Text one person 'Hope you have a good day'", "energy": "low", "reward": 10, "is_micro": True},
    {"name": "Physiology Reset", "sustainable": "3 deep belly breaths", "energy": "low", "reward": 5, "is_micro": True},
    {"name": "The 5-Minute Scrub", "sustainable": "Wash exactly 3 dishes", "energy": "med", "reward": 15, "is_micro": False},
    {"name": "Cognitive Anchor", "sustainable": "Write down today's 'One Big Thing'", "energy": "med", "reward": 10, "is_micro": True},
    {"name": "Deep Clean", "sustainable": "Clear and wipe one surface completely", "energy": "high", "reward": 25, "is_micro": False},
    {"name": "Movement Flow", "sustainable": "10 minutes of stretching or sun salutations", "energy": "high", "reward": 30, "is_micro": False},
    {"name": "Hydration Spike", "sustainable": "Drink 500ml of water right now", "energy": "low", "reward": 5, "is_micro": True},
    {"name": "Inbox Zero (Draft)", "sustainable": "Archive 5 old emails", "energy": "med", "reward": 10, "is_micro": False},
    {"name": "Dopamine Fast", "sustainable": "Stay away from phone for 10 mins", "energy": "high", "reward": 20, "is_micro": False},
    {"name": "Desk Zen", "sustainable": "Throw away 3 pieces of trash", "energy": "low", "reward": 5, "is_micro": True},
    {"name": "Brain Unload", "sustainable": "Write for 2 minutes in Brain Dump", "energy": "med", "reward": 10, "is_micro": True},
    {"name": "Visual Sort", "sustainable": "Organize one drawer for 5 mins", "energy": "high", "reward": 25, "is_micro": False},
    {"name": "Sun Exposure", "sustainable": "Stand by window with sun on skin for 2 mins", "energy": "low", "reward": 8, "is_micro": True},
    {"name": "Audio Focus", "sustainable": "Listen to 1 focus track without distractions", "energy": "med", "reward": 12, "is_micro": False},
    {"name": "Energy Burst", "sustainable": "Do 10 jumping jacks", "energy": "high", "reward": 15, "is_micro": True},
    {"name": "Gratitude Check", "sustainable": "Name 3 small wins from today", "energy": "low", "reward": 10, "is_micro": True},
    {"name": "Task Initiation", "sustainable": "Work on a avoided task for exactly 2 mins", "energy": "med", "reward": 15, "is_micro": True},
    {"name": "Social Connect", "sustainable": "Like or comment on a friend's post", "energy": "low", "reward": 5, "is_micro": True},
    {"name": "Nutritional Hit", "sustainable": "Eat one piece of fruit/veg", "energy": "med", "reward": 10, "is_micro": False},
    {"name": "Deep Work Block", "sustainable": "30 minutes of deep work (use Aura Mode)", "energy": "high", "reward": 50, "is_micro": False},
]

# Daily Quest Pool (Mental Health & ADHD Support)
DAILY_QUEST_POOL = [
    {"title": "Digit Detox", "desc": "No screens for the first 15 mins of waking up", "category": "mindfulness"},
    {"title": "Hydration Station", "desc": "Drink a full glass of water before your first coffee", "category": "health"},
    {"title": "The 'Done' List", "desc": "Write down 3 things you finished today, no matter how small", "category": "mindfulness"},
    {"title": "Social Spark", "desc": "Reply to that one message you've been avoiding", "category": "social"},
    {"title": "Environment Refresh", "desc": "Open a window and let fresh air in for 10 mins", "category": "health"},
    {"title": "Self-Compassion", "desc": "Speak one kind sentence to yourself in the mirror", "category": "mindfulness"},
    {"title": "Tab Cleanse", "desc": "Close all browser tabs that you haven't used in 2 days", "category": "focus"},
    {"title": "Nature Gaze", "desc": "Look at a plant or out of a window for 2 minutes straight", "category": "mindfulness"},
    {"title": "Mindful Sip", "desc": "Drink a beverage slowly, noticing the temperature and taste", "category": "mindfulness"},
    {"title": "Notification Purge", "desc": "Turn off non-essential notifications for one app", "category": "focus"},
    {"title": "Mirror Smile", "desc": "Give yourself a 5-second sincere smile in the mirror", "category": "social"},
    {"title": "Space Clear", "desc": "Remove one object from your workspace that doesn't belong", "category": "health"},
    {"title": "Focus Breath", "desc": "Do 5 rounds of box breathing (4-4-4-4)", "category": "mindfulness"},
    {"title": "Body Scan", "desc": "Close eyes and notice where you hold tension for 1 min", "category": "health"},
    {"title": "Future Self", "desc": "Do one small thing that will help your 'tomorrow self'", "category": "focus"},
    {"title": "Gratitude Spark", "desc": "Notice one thing you're glad you have right now", "category": "mindfulness"},
    {"title": "Desk Reset", "desc": "Wipe down your desk or keyboard", "category": "health"},
    {"title": "Posture Check", "desc": "Sit up straight and roll your shoulders back", "category": "health"},
    {"title": "Ear Candy", "desc": "Listen to one song you love with full attention", "category": "social"},
    {"title": "Task Slice", "desc": "Break one big task into 5 tiny micro-steps", "category": "focus"},
    {"title": "Water Flush", "desc": "Drink 250ml of water before your next meal", "category": "health"},
    {"title": "Sky Look", "desc": "Look at the sky for 30 seconds to reset vision", "category": "health"},
    {"title": "Kind Reply", "desc": "Send a short message of appreciation to someone", "category": "social"},
]

# Physical Kinetics - Hypertrophy and Strength focus (Underweight Support)
EXERCISE_PRESETS = [
    {"name": "Compound Push-ups", "sustainable": "3 wide push-ups on knees/toes", "energy": "high", "reward": 15, "icon": "💪", "desc": "Targets chest, shoulders, and triceps. Great for upper body volume."},
    {"name": "Foundation Squats", "sustainable": "5 deep air squats", "energy": "med", "reward": 12, "icon": "🦵", "desc": "Full lower body engagement. Essential for leg hypertrophy."},
    {"name": "Reverse Lunges", "sustainable": "4 lunges (2 per leg)", "energy": "high", "reward": 15, "icon": "🚶", "desc": "Focuses on stability and leg strength without heavy joint stress."},
    {"name": "Chair Dips", "sustainable": "3 slow dips on a chair", "energy": "med", "reward": 10, "icon": "🪑", "desc": "Isolated tricep and shoulder work for upper body definition."},
    {"name": "Core Plank", "sustainable": "Hold plank for 15 seconds", "energy": "low", "reward": 8, "icon": "🧱", "desc": "Deep core stability. Keeps you aligned for other compound movements."},
    {"name": "Glute Bridges", "sustainable": "5 hip thrusts on floor", "energy": "low", "reward": 8, "icon": "🍑", "desc": "Targets the posterior chain safely. Great for posture."},
]
